# Generated by Django 3.0.7 on 2020-07-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('duration', models.CharField(choices=[('One manth', 'One manth'), ('Two manths', 'Two manths'), ('Tree manths', 'Tree manths')], default='One manth', max_length=30)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Beauty, Care and Health', 'Beauty, Care and Health'), ('Fation', 'Fation'), ('Home Products', 'Home Products')], default='Food', max_length=30)),
                ('areas', models.CharField(choices=[('Tel-Aviv', 'Tel-Aviv'), ('Jerusalem', 'Jerusalem'), ('North', 'North')], default='Tel-Aviv', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('display', models.CharField(choices=[('High-Way', 'High-Way'), ('Urban', 'Urban'), ('Inter-Urban-Roads', 'Inter-Urban-Roads')], default='High-Way', max_length=20)),
                ('percent', models.CharField(choices=[('10%', '10%'), ('20%', '20%'), ('30%', '30%'), ('40%', '40%'), ('50%', '50%'), ('60%', '60%'), ('70%', '70%'), ('80%', '80%'), ('90%', '90%'), ('100%', '100%')], default='10%', max_length=20)),
                ('day', models.CharField(choices=[('High-Way', 'High-Way'), ('Urban', 'Urban'), ('Inter-Urban-Roads', 'Inter-Urban-Roads')], default='Morning', max_length=20)),
            ],
        ),
    ]
