# Generated by Django 2.2.13 on 2020-07-09 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_auto_20200708_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='campaign',
        ),
    ]
