# Generated by Django 2.2.13 on 2020-07-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_remove_file_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('process', 'process'), ('done', 'done'), ('wait', 'wait')], default='wait', max_length=20),
        ),
    ]
