# Generated by Django 2.2.13 on 2020-07-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_campaign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='file',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
