# Generated by Django 2.2.13 on 2020-07-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0007_auto_20200709_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='picture',
            field=models.ImageField(default='', upload_to='ad_pictures'),
        ),
        migrations.AddField(
            model_name='file',
            name='picture',
            field=models.ImageField(default='', upload_to='ad_pictures'),
        ),
    ]
