# Generated by Django 2.2.13 on 2020-07-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0008_auto_20200709_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='picture',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
