# Generated by Django 2.2.13 on 2020-07-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0009_auto_20200709_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='picture',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='picture',
            field=models.ImageField(default='', upload_to='campaign/images'),
        ),
    ]
