# Generated by Django 2.2.13 on 2020-07-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0011_auto_20200711_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('process', 'process'), ('done', 'done'), ('wait', 'wait')], default='wait', max_length=20),
        ),
    ]
