# Generated by Django 2.2.13 on 2020-07-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0015_auto_20200711_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='display',
            new_name='RoadType',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='areas',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='status',
        ),
        migrations.RemoveField(
            model_name='file',
            name='day',
        ),
        migrations.RemoveField(
            model_name='file',
            name='url',
        ),
        migrations.AddField(
            model_name='campaign',
            name='around',
            field=models.CharField(choices=[('schools', 'schools'), ('Offices', 'Offices'), ('shopping centers', 'shopping centers')], default='shools', max_length=50),
        ),
        migrations.AddField(
            model_name='campaign',
            name='location',
            field=models.CharField(choices=[('Tel Aviv Metropolitan Area', 'Tel Aviv Metropolitan Area'), ('Jerusalem', 'Jerusalem'), ('North', 'North'), ('South', 'South')], default='Tel Aviv Metropolitan Area', max_length=50),
        ),
        migrations.AddField(
            model_name='file',
            name='dayTime',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Noon', 'Noon'), ('Evening', 'Evening')], default='Morning', max_length=20),
        ),
        migrations.AddField(
            model_name='file',
            name='picture',
            field=models.ImageField(default='', upload_to='campaign/images'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='duration',
            field=models.CharField(choices=[('One week', 'One week'), ('Two weeks', 'Two weeks'), ('one month', 'One month')], default='One week', max_length=30),
        ),
    ]
