# Generated by Django 2.2.13 on 2020-07-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0017_campaign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
