# Generated by Django 2.2.13 on 2020-07-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0023_auto_20200711_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
