# Generated by Django 2.2.13 on 2020-07-11 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0024_auto_20200711_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='slug',
        ),
    ]
