# Generated by Django 2.2.13 on 2020-07-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0025_remove_campaign_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='url',
        ),
        migrations.AddField(
            model_name='campaign',
            name='num_file',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1),
        ),
    ]
