# Generated by Django 2.2.13 on 2020-07-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0035_profile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
