# Generated by Django 2.2.13 on 2020-07-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0036_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='"../images/profile.png"', upload_to='campaign/images'),
        ),
    ]
